name: BlockFreezer
main: blockfreezer.BlockFreezer
version: 1.1.0
api: 1.0.0
load: POSTWORLD
author: Gamecrafter
description: Control what blocks update in your worlds!
website: https://github.com/Viperize/BlockFreezer-Nukkit
permissions:
 blockfreezer:
  default: op
  children:
   blockfreezer.command:
    default: op
    children:
     blockfreezer.command.blockfreezer:
      default: op